### ISSUE TITLE
Skript API

### ISSUE THREAD

**Issue by an0nim0wy** [xVacuum/qEssentialsReloaded#1]
Może by tak dodać api dla skryptów?
(mogę pomóc :>)

**Comment by xVacuum** [comment]
[Takie?](https://github.com/TheMolkaPL/FunnyGuilds/blob/mc1.9/src/main/java/net/dzikoysk/funnyguilds/listener/G%C3%B3wno.java)

**Comment by an0nim0wy** [comment]
Aaaa... to juz wiem czemu taki komunikat się pojawiał xd. Mozna zrobic cos pokroju tego: https://github.com/an0nim0wy/ySkriptAddon

Moge takze dodac wsparcie qEss w powyzszym pluginie, jednak lepszym rozwiazaniem bedzie zrobienie to w qEssesie. Nawet moge to za Ciebie zrobic - nudzi mi sie w ch*j :D

**Comment by xVacuum** [comment]
Nope, nie zamierzam wspierać tego shitu.
