### ISSUE TITLE
Komenda /s lub /tphere

### ISSUE THREAD

**Issue by Fixuuu** [xVacuum/qEssentialsReloaded#2]
Prosze o dodanie /s lub /tphere ;)

**Comment by Fixuuu** [comment]
Oraz /pt jak w essentials

**Comment by xVacuum** [comment]
Co robi */pt* i */s*?
*/tphere* zostanie dodane.

**Comment by TheMolkaPL** [comment]
`/s` to alias do `/tphere`.

**Comment by Fixuuu** [comment]
/s - /tphere a /pt np. trzymasz miecz diax i piszesz /pt give Fixuuu stone 1 np. czyli jak klikniesz lewym na ten miecz to dostajesz item a jesli chcesz to usunac piszesz znow /pt na tym itemku ;) Sprawdz source code od essentialsa i sobie przepisz czy cuus ;x

**Comment by an0nim0wy** [comment]
Ok, tylko pomyśl. Po co to?

**Comment by xVacuum** [comment]
@Fixuuu To nie byłby problem, dałbym np. w lore komendę która by się wykonywała. Ale czy jest sens?

**Comment by Fixuuu** [comment]
Nwm a i daj do chat formatu {PREFIX} z pexa bo nie dziala ;x
http://scr.hu/2kql/sfiv3

**Comment by xVacuum** [comment]
Musi działać, napewno poprawnie zainstalowałeś Vaulta i PermissionsEx?

**Comment by Fixuuu** [comment]
Nie wgralem vaulta ;x Ahh ja ten debil napisz w opsie czy cuus

**Comment by xVacuum** [comment]
Jest napisane w logach 
`[11:02:35 INFO]: [qEssentialsReloaded] [Misc] Loading FunnyGuilds optionally...
[11:02:35 INFO]: [qEssentialsReloaded] [Misc] FunnyGuilds found, enabling tab variables...
[11:02:35 INFO]: [qEssentialsReloaded] [Misc] Loading Vault optionally...
[11:02:35 INFO]: [qEssentialsReloaded] [Misc] Vault found, enabling vault functions...`

lub `[qEssentialsReloaded] [Misc] Vault missing, disabling vault functions...`
Wszystko jest napisane! :)

**Comment by Fixuuu** [comment]
ok jeszcze w nastepnej dodaj do tabu jak w gildia qguilds ze glowy widac np. z twoim skinem np. skkf czy inne ;)

**Comment by Fixuuu** [comment]
Znalazlem blad ;x nie moze byc np. {FG/POINTS} tylko jak na ss'ie ;x
http://scr.hu/2kql/saae9

**Comment by Fixuuu** [comment]
Wiem ze to nie qessentialsa blad ale bedzie trzeba to robic w fg wiec chyba lepiej w qess

**Comment by xVacuum** [comment]
Tak musi być, bo kiedyś będa wsparcia do innych pluginów i mogą się mieszać zmienne.

**Comment by Fixuuu** [comment]
aha a kiedy wrzucasz new wersje ? :+1:

**Comment by xVacuum** [comment]
Dodano komendy.
