### ISSUE TITLE
Nowe komendy

### ISSUE THREAD

**Issue by Fixuuu** [xVacuum/qEssentialsReloaded#3]
Komenda /tppos [x] [y] [z] i zapomnialem przypomni mi sie to napisze xd

**Comment by xVacuum** [comment]
Mhm. Zostanie dodane.

**Comment by Fixuuu** [comment]
Szybka reakcja xd

**Comment by xVacuum** [comment]
Bo mi się nudzi i szukam propozycji.

**Comment by Fixuuu** [comment]
Ja tez szukam fajnych rzeczy ktore mogl bys dodac, zebys sie za bardzo nie nudzil xd

**Comment by Fixuuu** [comment]
Mozliwosc zmieniania w configu prefixa i suffixa albo ich usuwania /bc ;)

**Comment by Fixuuu** [comment]
Komenda /itemname i /lore np. : x

**Comment by xVacuum** [comment]
@Fixuuu na cholerę itemname i lore? Przecież masz /i apple nazwa lore;lore enchanty
Prefix/suffix to już takie na siłe, bez sensu ;/

**Comment by Fixuuu** [comment]
ok ;x ale mi chodzi zeby nie bylo o to zobacz ss'a
http://scr.hu/2kql/4kvo0

**Comment by xVacuum** [comment]
Przecież to można w configu zmienić xD (messages_pl.yml)

**Comment by Fixuuu** [comment]
Aha ok thx

**Comment by OddiPlugins** [comment]
Ja proszę o komendę /unban /ban /tempban

**Comment by OddiPlugins** [comment]
I jak mogę wiedzieć jaki jest prefix pokazywania gildi w formacie chatu

**Comment by xVacuum** [comment]
Możesz prosić, nie zostanie dodane, plugin jest na podstawowe funkcje ;_; wgraj coś dobrego na bany, z supportem np. stron internetowych, parę takich widziałem.

Takie jak w FunnyGuilds, z tego co wiem to chyba {TAG}, jeżeli o to ci chodzi.

**Comment by Fixuuu** [comment]
np. HugoBans sa dobre i AdvancedBans albo MaxBans

**Comment by Fixuuu** [comment]
Komenda /kill [player] albo siebie ;)

**Comment by xVacuum** [comment]
@Fixuuu myślałem nad tym, bo wczoraj mi tego zabrakło, dodam.

**Comment by Fixuuu** [comment]
Spk mysle czego brakuje ;( nie wiem co moze sudo ;)

**Comment by Fixuuu** [comment]
Moze kit w menu? :)

**Comment by Fixuuu** [comment]
Wiem ze to troche trude ale jakis maly antycheat? :)

**Comment by Fixuuu** [comment]
Powiekszany enderchest z uprawnieniem :) jak na easyh*rd.net

**Comment by Fixuuu** [comment]
@xVacuum Do zamkniecia ;)
