### ISSUE TITLE
Poprawienie home i dodanie /warp

### ISSUE THREAD

**Issue by Fixuuu** [xVacuum/qEssentialsReloaded#4]
Prosze o dodadnie /warp i zrobienie, ze jak jest tylko jeden home to tepa na niego nie trzeba wpisywac nazwy :) i ilosc home pod permssia np. qessentials.home.limit.vip i w config ustawiasz ze ma byc 2 czy ile sie chce i tak samo z graczem :)

**Comment by xVacuum** [comment]
Nie zrobię tak ponieważ po wpisaniu `/home` jest wyświetlana lista domów :) 
Ilość homów dodam a /warp w sumie mało potrzebne, ale dodam.

**Comment by xVacuum** [comment]
Po prostu dodam uprawnienia `qessentials.home.limit.<ilosc>`

**Comment by Fixuuu** [comment]
ok

**Comment by Fixuuu** [comment]
A tak apropo bedziesz dokanczac qGuilds2?

**Comment by xVacuum** [comment]
@Fixuuu nie.

**Comment by xVacuum** [comment]
Dodano uprawnienie jak i komendy `/warp`
Zamykam.
