### ISSUE TITLE
Nowe komendy

### ISSUE THREAD

**Issue by Fixuuu** [xVacuum/qEssentialsReloaded#5]
- Komenda /mute <nick> <czas> - blokowała by pisanie na czacie przez dany czas
- /banip <ip> <powod> - banowała by graczy na ip
- /seen <nick/ip>:
   * nick - pokazywało by ip gracza, oraz kiedy ostatni raz był online
   * ip - pokazywało by wszystkie konta zarejestrowane na danym ip
- /craft - otwierała by wirtualny crafting
- /banlist - wyświetlała by wszystkich zbanowanych graczy
- /banlistip - wyświetlała by wszystkie zbanowane ip

**Comment by xVacuum** [comment]
Coś tam robię powoli ;p btw. podasz gg jak masz?

![whois](https://i.gyazo.com/91b6a387c19e0077370401437d16cb7b.png)

**Comment by Fixuuu** [comment]
Spoczko. Juz pobiore gg i podam :)

**Comment by Fixuuu** [comment]
A te komendy w poscie na jakims forum znalazlem bo gosciu napisal

**Comment by Fixuuu** [comment]
59448094 zapros :)
