### ISSUE TITLE
tab

### ISSUE THREAD

**Issue by vpsvky1337** [xVacuum/qEssentialsReloaded#7]
na 1.10 spami tabem jak szalone ,a all dziala (cos z impl)

**Comment by vpsvky1337** [comment]
+ nie kazdy widzi header/footer buguje sie + jak sie nie zalogujesz np z authme to nie widzisz taba wgl masz krotki czarny pasek + nie dziala wgl tab jak sie zmieni config nadal sa gracze tylko header/footer dla 1 osoby ktora wbije dziala

**Comment by xVacuum** [comment]
Plugin nie jest wspierany póki co na `1.10`. Będzie aktualizacja jak tylko wynajdę jak napisać tab na `1.10`. To jak bawienie się w kotka i myszkę z mojangiem.

**Comment by vpsvky1337** [comment]
A kiedy poprawisz? To czm np ranking by bartzzdev (Chyba ten autor) dzialal mi na 1.10 z 1.8? kappa

**Comment by an0nim0wy** [comment]
Ponieważ tam tab został zrobiony, przy użyciu ProtocolLib'a.

**Comment by xVacuum** [comment]
`Naprawione, plugin został zaktualizowany do `1.10`.
